# Generated by Django 4.2.7 on 2025-05-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payments',
            name='receiptid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
